language: node_js
node_js:
  - "stable"
cache:
  directories:
    - node_modules
install:
  - yarn install
script:
  - yarn build
# deploy:
#   - provider: codedeploy
#     wait_until_deployed: true
#     revision_type: github
#     access_key_id: "YOUR AWS ACCESS KEY"
#     secret_access_key: "YOUR AWS SECRET KEY"
#     application: "Your Codedeploy application"
#     deployment_group: "The Deployment group associated with the codedeploy application"
#     region: "Region in which your ec2 instance is."
#     project: ./build/
on:
  branch: frontend
