name: Backend CI/CD

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events
  push:
    branches: [backend]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Redeploying the updated project
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST_B }}
          username: ${{ secrets.SSH_USER_B }}
          key: ${{ secrets.SSH_PRIVATE_KEY_B }}
          script: |
            cd backend/bounswe2020group6/backend
            git fetch origin backend
            git checkout origin/backend backend
            sudo docker build -t akademise/akademise .
            docker rm -f akademise/akademise
            sudo docker run -p 3000:3000 -d akademise/akademise
