# This is a basic workflow to help you get started with Actions

name: Frontend CI/CD

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events
  push:
    branches: [frontend]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: echoing
        run: |
          echo ${{secrets.SSH_HOST_F}} | sed -e 's/\(.\)/\1 /g'
          echo ${{secrets.SSH_USER_F}} | sed -e 's/\(.\)/\1 /g'
          echo ${{secrets.SSH_PRIVATE_KEY_F}} | sed -e 's/\(.\)/\1 /g'

      - name: Redeploying the updated project
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST_F }}
          username: ${{ secrets.SSH_USER_F }}
          key: ${{ secrets.SSH_PRIVATE_KEY_F }}
          script: |
            cd app
            git fetch origin frontend
            git checkout origin/frontend frontend
            cd frontend
            docker build -t akademise .
            docker image prune -f
            docker rm -f akademise-container
            docker run -d -p 80:80 --name akademise-container akademise
